version: '3.7'
services:
    webserver:
        container_name: node_cont
        build:
          context: .
          dockerfile: ./dockerfiles/node.dockerfile
        ports:
          - 3000:3000
        depends_on:
          - mongodb

    mongodb:
        container_name: mongodb_cont
        build:
          context: ./dockerfiles
          dockerfile: mongodb.dockerfile
        ports:
          - 27017:27017
        volumes:
          - mongovolume:/data/db

volumes:
  mongovolume:
